spring.application.name=backend
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/portalroshka}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
aws.accessKeyId=${AWS_ACCESS_KEY_ID:default}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY:default}
aws.region=${AWS_REGION:us-east-1}
topic.solicitud=${TOPIC_SOLICITUD:default}
topic.notificacion=${TOPIC_NOTIFICACION:default}
correo.th=${CORREO_TH:default}
correo.sa=${CORREO_SA:default}
region: sa-east-1
arn:aws:sns:sa-east-1:681721397478:portal-notificacion
arn:aws:sns:sa-east-1:681721397478:portal-solicitud
spring.main.allow-bean-definition-overriding=true
